security:
    providers:
        in_memory:
            memory:
                users:
                    juanlu:
                        password: '1234'
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        mi_area_segura:
            anonymous: ~
            provider: in_memory
            guard:
                authenticators:
                    - my_form_authenticator
            logout:
                path: logout_route
                target: homepage

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
